# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Marshmallow_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Marshmallow_iOS

  target 'Marshmallow_iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Marshmallow_iOSUITests' do
    # Pods for testing
  end

pod 'Alamofire'
pod 'Kingfisher'
pod 'SnapKit'


end
